CREATE TABLE IF NOT EXISTS web_reviews (
  id VARCHAR(50) PRIMARY KEY,
  guest_name VARCHAR(200) NOT NULL,
  rating INTEGER NOT NULL,
  comment TEXT NOT NULL,
  is_approved BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
